/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.willyan.vi.view;

import br.willyan.cont.dto.UsuarioC;
import br.willyan.mod.dao.UsuarioM;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Willyan
 */
public class formAcesso extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public formAcesso() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtfp_senha = new javax.swing.JPasswordField();
        jtf_nome_usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setText("Versão: 0.1A");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 975, 45, 10);

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(354, 263, 90, 30);

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 263, 90, 30);

        jtfp_senha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtfp_senha.setText("jPasswordField1");
        jtfp_senha.setBorder(null);
        jtfp_senha.setPreferredSize(new java.awt.Dimension(96, 14));
        jtfp_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfp_senhaMouseClicked(evt);
            }
        });
        jtfp_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfp_senhaActionPerformed(evt);
            }
        });
        jtfp_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfp_senhaKeyPressed(evt);
            }
        });
        getContentPane().add(jtfp_senha);
        jtfp_senha.setBounds(400, 210, 149, 14);

        jtf_nome_usuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtf_nome_usuario.setText("Digite seu login");
        jtf_nome_usuario.setBorder(null);
        jtf_nome_usuario.setPreferredSize(new java.awt.Dimension(74, 14));
        jtf_nome_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_nome_usuarioMouseClicked(evt);
            }
        });
        jtf_nome_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nome_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_nome_usuario);
        jtf_nome_usuario.setBounds(400, 176, 139, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/willyan/vi/view/background_form.png"))); // NOI18N
        jLabel7.setText("   ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        acessar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfp_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfp_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfp_senhaActionPerformed

    private void jtf_nome_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_nome_usuarioMouseClicked
        jtf_nome_usuario.setText("");
    }//GEN-LAST:event_jtf_nome_usuarioMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfp_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfp_senhaMouseClicked
        jtfp_senha.setText("");
    }//GEN-LAST:event_jtfp_senhaMouseClicked

    private void jtf_nome_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nome_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nome_usuarioActionPerformed

    private void jtfp_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfp_senhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfp_senhaKeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void acessar() {
        String nome, senha;
        nome = jtf_nome_usuario.getText();
        senha = jtfp_senha.getText();

        UsuarioC c_usuario = new UsuarioC();
        c_usuario.setNome(nome);
        c_usuario.setSenha(senha);

        UsuarioM m_usuario = new UsuarioM();
        ResultSet rsm_usuario = null;
        try {

            try {
                rsm_usuario = m_usuario.rs_aut(c_usuario);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(formAcesso.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (rsm_usuario.next()) {
                //formPrincipal principal = new formPrincipal();
                //principal.setLocationRelativeTo(null);
                //principal.setVisible(true);

                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        formPrincipal principal = new formPrincipal();
                        principal.setVisible(true);
                    }
                });

                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou Senha incorreta");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha ao rodar Acesso: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new formAcesso().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtf_nome_usuario;
    private javax.swing.JPasswordField jtfp_senha;
    // End of variables declaration//GEN-END:variables
}
